apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vicizth3i-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vicizth3i-go 
  name: vicizth3i-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vicizth3i-go 
